Solves issue no #171
GrabBits/GrabBits_Website pull request #174
Opened 2023-06-12 03:24 UTC by Monson2002

## Related Issue

Closes: #171 

## Description of Changes

I've added a function which will capitelize the first letter of the passed argument into the search bar which will improve the searching in "Opportunity" section.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Videos
## Before

https://github.com/GrabBits/GrabBits_Website/assets/91113152/26467555-405b-4ae1-ab67-7478503cdeff

## After

https://github.com/GrabBits/GrabBits_Website/assets/91113152/435b6478-b41e-46da-97b8-7b6a4da1c452

2023-06-12 17:30 UTC, Monson2002 commented
@SaurabhBarde-007 can you review this?

2023-06-13 18:41 UTC, Grab-Bits commented
Hey @Monson2002 , Great job with the issue !!
But we will need a slight more changes from your side that we don't have to send api req for every letter entered rather it should search within the given array thus giving a fast and efficient output !!
I hope you get it!

2023-06-14 09:22 UTC, Monson2002 commented
So that means I have to fetch the data of all Opportunities once I visit the page, store it in an array and then search in the array. Am I right?

2023-06-14 18:28 UTC, Grab-Bits commented
>
Yes exactly, prefer using the useMemo hook to implement efficiently !!

2023-06-16 14:15 UTC, Monson2002 commented
@Grab-Bits can you check my changes now, I've used an array to store all job details the first time when visiting. All further operations on searching are done on the array itself without calling the API again and again, thus calling the API just once.

2023-06-16 20:06 UTC, Grab-Bits requested changes

2023-06-16 20:06 UTC, Grab-Bits commented on client/src/components/Opportunities/Opportunities.jsx
> +			console.log("Some Error");
there is a slight error in this else statement, I guess you will have think more on it 
In case of any help , you can ping me on discord !!

2023-06-17 04:36 UTC, Monson2002 reviewed
@Grab-Bits  I have set the "jobData" array to "jobArray" once the search bar is empty once the user deletes what he has written in the search bar, is this the change you were expecting ?
`		}else{`
`			setJobData(jobArray);`
`		}`
`

2023-06-17 18:39 UTC, Bhushan8177 commented
> @Grab-Bits I have set the "jobData" array to "jobArray" once the search bar is empty once the user deletes what he has written in the search bar, is this the change you were expecting ? ` }else{` ` setJobData(jobArray);` ` }` `

Yes, it was one of the changes required but to make it more efficient I want to implement useMemo hook here so as to not render the list all the time until there is no new opportunity from the api,  what it will do is fetch for just the first time you enter the website and then we can do indefinite searches and filters without any worries !!

2023-06-19 12:49 UTC, closed without merging