Refactoring "SERVER" folder structure.
GrabBits/GrabBits_Website pull request #61
Opened 2023-05-24 11:29 UTC by Ayushparui

## Related Issue

### ISSUE in the folder Structure

The `config.js`  file is exposed to the root server folder making it vulnerable.

### TITLE

1. The aim of this PR is to Refactor the **SERVER** folder structure, by creating a separate **_Utils_** folder for referencing environment variables.

2. Changing the **_config_** folder name to **_database_** .

Closes: #53 

## Description of Changes

1. Changed the **config** folder name to **database**.
2. Created a separate **utils** folder for accessing _ENVIRONMENT_VARIABLES_
3. Changed Code into several files which include `(mailer.js , user.controller.js , db.js , middleware/auth.js , middleware/errorMiddleware.js , Index.js)`

## Accessing Environment Variables

 To access _ENVIRONMENT_VARIABLES_ go to **utils** folder and add configuration _(eg. OTP: process.env.OTP || "123456")_ and importing to files _(eg. import {Server} from "../utils/config.js")_ and add where the OTP is required _(eg. var otp = Server.OTP)_

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.

**@GSSOC23**

2023-05-24 20:40 UTC, Spyware007 commented
Hello @Ayushparui I have to test it.
It may take a while to merge this PR.

2023-05-25 11:15 UTC, kuvamdazeus requested changes
Great work @Ayushparui 

I've suggested some changes here, please accommodate them into the PR & then we can merge it :)

Thanks for your contribution!

2023-05-25 11:15 UTC, kuvamdazeus commented on server/utils/config.js
Hi @Ayushparui please add here the following:

```javascript
import dotenv from 'dotenv'

dotenv.config()
```

so that it can actually read the env variables, currently it is defaulting to the OR values even when using `.env` file..

2023-05-25 11:15 UTC, kuvamdazeus commented on server/database/db.js
Hi @Ayushparui 

under the console.log statement,
please add

```javascript
mongoose.set("strictQuery", true)
```

To suppress the unnecessary warning in the console.

2023-05-25 11:17 UTC, kuvamdazeus commented
Also, please take a pull from the main branch, I did some changes there...

2023-05-25 14:12 UTC, Ayushparui commented
hello @kuvamdazeus I made the change as you said have a look at it and let me know, if everything's perfect.

2023-05-25 15:17 UTC, kuvamdazeus approved these changes
Seems nice

2023-05-25 15:17 UTC, merged